# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 54eb22e256d806d69801cb1ced034c3705f4025cf07631e853829481128e32e4f0c92496332e01e1edff69296020d8e4373be8b79eb5d9bbf4e3c265e11ec40a

test:
  secret_key_base: 89a0a197fbd2799343151090cf714573ec1efcfa6268bf3f1fa9790ee9e5c14d637554378204c0e38e4be31ae9062fde954c68ed802905b6dd83b7c268104ff0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
